### ISSUE TITLE
TensorFlow Issues

### ISSUE THREAD

**Issue by FluffehWalrus** [hanhung/Creating-Audio-Reactive-Visuals-With-StyleGAN#1]
Hey

Would it be possible to include a requirements.txt for use with pip when installing python libraries.

I am currently using your repo and facing issues when running gen_images (see below output) which I assume might be related to my tensorflow version (tensorflow 2.1.0)

```
python gen_images.py --model_path network-snapshot-008040.pkl
2020-04-28 14:28:57.708914: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-28 14:28:57.712029: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "gen_images.py", line 22, in <module>
    import dnnlib.tflib as tflib
  File "resource/stylegan\dnnlib\tflib\__init__.py", line 8, in <module>
    from . import autosummary
  File "resource/stylegan\dnnlib\tflib\autosummary.py", line 31, in <module>
    from . import tfutil
  File "resource/stylegan\dnnlib\tflib\tfutil.py", line 34, in <module>
    def shape_to_list(shape: Iterable[tf.Dimension]) -> List[Union[int, None]]:
AttributeError: module 'tensorflow' has no attribute 'Dimension'
```

Thanks

**Comment by lucaskuzma** [comment]
Came here looking for the same thing. Could someone do a `pip freeze` or equivalent? 🙏
