### ISSUE TITLE
PySound -- Librosa

### ISSUE THREAD

**Issue by aevin-io** [hanhung/Creating-Audio-Reactive-Visuals-With-StyleGAN#2]
```UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/scipy/signal/_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]
Traceback (most recent call last):
  File "feature_extraction.py", line 35, in <module>
    librosa.output.write_wav(out_dir + 'lpf_y.wav', lpf_y, sr)
AttributeError: module 'librosa' has no attribute 'output'```

Although a warning, the features cannot be extracted properly

**Comment by hanhung** [comment]
I think it is because of the librosa version. Maybe you can try using soundfile to write the file like here: https://librosa.org/doc/latest/ioformats.html#write-out-audio-files, or you can try downgrading to 0.6.0.

**Comment by ShamalLakshan** [comment]
Downgraded to 0.6.0. And there,s another error
```

Traceback (most recent call last):
  File "/home/lucifer/coding/Test-Field/Creating-Audio-Reactive-Visuals-With-StyleGAN/feature_extraction.py", line 8, in <module>
    import librosa
  File "/home/lucifer/.local/lib/python3.9/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/lucifer/.local/lib/python3.9/site-packages/librosa/core/__init__.py", line 102, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/lucifer/.local/lib/python3.9/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/home/lucifer/.local/lib/python3.9/site-packages/librosa/util/__init__.py", line 70, in <module>
    from . import decorators
  File "/home/lucifer/.local/lib/python3.9/site-packages/librosa/util/decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators
```
